name: bid_on_a_box_final
description: Final bid on a box project

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^0.3.0
  numberpicker: ^1.1.0
  quiver: '>=2.0.0 <3.0.0'
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/auction_box.png
    - assets/recipe_image.png
    - assets/food_waste.png
    - assets/assorted_veg.png
    - assets/produce_basket.jpg
    - assets/veg_box.jpg
    - assets/waitrose_map.png
    - assets/paper_map.png
    - assets/chicken_jambalaya.jpg
    - assets/chicken_cream_cheese.jpg
    - assets/spring-lamb.jpg
    - assets/bbq_lamb_pilaf.jpg
    - assets/spanish-chicken-stew.jpg
    - assets/vege-tagine-with-apricot-quinoa.jpg
    - assets/raspberry-pistachio-lemon-curd-trifles.jpg
    - assets/love_food.jpg
    - assets/wrap.png
    - assets/think_eat_save.jpg
    - assets/Waitrose.jpg
    - assets/Sainsburys.jpg
    - assets/tesco.jpg
    - assets/Aldi.png
    - assets/sainsburys_dennison.png
    - assets/lidl_priory.png
    - assets/asda_superstore.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
